title: Andrew Feierman's Blog
description: My Blog. What I do and what I'm interested in.
author: Andrew Feierman
logo: /afeierman.github.io/static/img/andrew_github.png
github: https://github.com/afeierman
about: Data Scientist knowledgeable about sustainability and housing.

baseurl: ""
url: ""

allowsearch: true

#google_analytics:

share:
  twitter_username: /afeierman
#  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
